# Generated by Django 6.0.3 on 2026-03-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(help_text='bcrypt 해시', max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', '학생/구직자'), ('company', '기업 담당자'), ('admin', '플랫폼 관리자')], default='student', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_consent', models.BooleanField(default=False, help_text='AI 이용 동의')),
                ('privacy_consent', models.BooleanField(default=False, help_text='개인정보 수집 동의')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('curriculum', '커리큘럼 생성'), ('weakness', '취약점 분석'), ('recommendation', '문제 추천'), ('portfolio', '포트폴리오 생성'), ('matching', '채용 매칭'), ('problem_gen', '문제 자동 생성')], max_length=20)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='API 응답 지연(ms)', null=True)),
                ('status', models.CharField(choices=[('success', '성공'), ('error', '에러'), ('timeout', '타임아웃'), ('cached', '캐시 히트')], default='success', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='배치 작업은 NULL, 사용자 탈퇴 시 SET NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='관리자 승인 여부')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, help_text='필수 기술 스택 배열', null=True)),
                ('preferred_skills', models.JSONField(blank=True, help_text='우대 기술 스택 배열', null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('career_level', models.CharField(choices=[('new', '신입'), ('junior', '주니어 (1~3년)'), ('senior', '시니어 (3년+)'), ('any', '경력 무관')], default='any', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='LearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('language', '언어별'), ('algo_tag', '알고리즘 태그별')], max_length=15)),
                ('stat_key', models.CharField(help_text='"Python" 또는 "정렬"', max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='총 시도 수')),
                ('solved_count', models.PositiveIntegerField(default=0, help_text='정답 수')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='오답 수')),
                ('correct_rate', models.FloatField(blank=True, help_text='solved_count / total_count * 100', null=True)),
                ('last_solved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(blank=True, help_text='AI 매칭 점수 (0~100)', null=True)),
                ('status', models.CharField(choices=[('recommended', '시스템 추천'), ('viewed', '열람'), ('scrapped', '스크랩'), ('applied', '지원 완료'), ('rejected', '불합격')], default='recommended', max_length=15)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('baekjoon', '백준'), ('github', 'GitHub'), ('programmers', '프로그래머스')], max_length=20)),
                ('external_id', models.CharField(help_text='플랫폼 username / handle', max_length=200)),
                ('access_token', models.CharField(blank=True, help_text='OAuth 토큰 — AES-256 암호화 후 저장', max_length=500, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='나의 개발자 포트폴리오', max_length=300)),
                ('summary_text', models.TextField(blank=True, help_text='Gemini 생성 역량 요약', null=True)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('public_slug', models.SlugField(blank=True, help_text='공개 URL: /portfolio/{slug}', max_length=120, null=True, unique=True)),
                ('pdf_path', models.CharField(blank=True, help_text='서버 내 PDF 파일 경로', max_length=500, null=True)),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', '영어')], default='ko', max_length=5)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_public', models.BooleanField(default=True, help_text='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('contest', '대회 정보'), ('event', '이벤트')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='상단 고정')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='ON DELETE RESTRICT — 관리자 계정 보호', on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('baekjoon', '백준'), ('programmers', '프로그래머스'), ('w3schools', 'W3Schools'), ('custom', 'ELAW 자체 문제')], max_length=20)),
                ('problem_id', models.CharField(help_text='플랫폼 내 문제 번호/코드', max_length=50)),
                ('problem_title', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('solved', '정답'), ('failed', '오답'), ('partial', '부분 정답')], max_length=10)),
                ('language', models.CharField(blank=True, help_text='Python, Java, C++ 등', max_length=50, null=True)),
                ('algo_tags', models.JSONField(blank=True, help_text='알고리즘 태그 배열', null=True)),
                ('difficulty', models.CharField(blank=True, help_text='Bronze5, Silver3, Level2 등', max_length=30, null=True)),
                ('time_spent_min', models.SmallIntegerField(blank=True, help_text='풀이 소요 시간(분)', null=True)),
                ('solved_at', models.DateTimeField(help_text='실제 풀이 완료 시각')),
                ('source', models.CharField(choices=[('api', 'API 자동 수집'), ('crawl', '크롤링 수집'), ('manual', '사용자 직접 입력')], default='api', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('study', '공부'), ('job', '취업')], max_length=10)),
                ('field', models.CharField(blank=True, help_text='컴퓨터, 전기, 조선, 토목, 건축 등', max_length=100, null=True)),
                ('job_role', models.CharField(blank=True, help_text='백엔드, AI 개발자, 데이터 엔지니어 등', max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mid_eval_date', models.DateField(blank=True, help_text='중간 평가일', null=True)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='현재 활성 목표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.JSONField(help_text='Gemini 생성 주차별 학습 계획 전체')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='재생성 시 1씩 증가')),
                ('is_active', models.BooleanField(default=True, help_text='현재 사용 중인 커리큘럼')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='core.usergoal')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_users_created_at'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['user', 'feature'], name='idx_ai_logs_user_feature'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['-created_at'], name='idx_ai_logs_created_at'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['status'], name='idx_ai_logs_status'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_approved'], name='idx_companies_approved'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'is_active'], name='idx_job_postings_company'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_role'], name='idx_job_postings_role'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['deadline', 'is_active'], name='idx_job_postings_deadline'),
        ),
        migrations.AddIndex(
            model_name='learningstats',
            index=models.Index(fields=['user', 'correct_rate'], name='idx_stats_correct_rate'),
        ),
        migrations.AlterUniqueTogether(
            name='learningstats',
            unique_together={('user', 'stat_type', 'stat_key')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user', '-match_score'], name='idx_matches_user_score'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['posting', 'status'], name='idx_matches_posting_status'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user', 'posting')},
        ),
        migrations.AddIndex(
            model_name='platformlink',
            index=models.Index(fields=['last_synced'], name='idx_platform_links_synced'),
        ),
        migrations.AlterUniqueTogether(
            name='platformlink',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='idx_portfolios_user_id'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_public', '-created_at'], name='idx_portfolios_public'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='idx_posts_category_date'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='idx_posts_pinned'),
        ),
        migrations.AddIndex(
            model_name='solvehistory',
            index=models.Index(fields=['user', '-solved_at'], name='idx_solve_user_solved_at'),
        ),
        migrations.AddIndex(
            model_name='solvehistory',
            index=models.Index(fields=['platform'], name='idx_solve_platform'),
        ),
        migrations.AddIndex(
            model_name='solvehistory',
            index=models.Index(fields=['language'], name='idx_solve_language'),
        ),
        migrations.AlterUniqueTogether(
            name='solvehistory',
            unique_together={('user', 'platform', 'problem_id')},
        ),
        migrations.AddIndex(
            model_name='usergoal',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_goals_active'),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['user', 'is_active'], name='idx_curricula_user_active'),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['goal'], name='idx_curricula_goal'),
        ),
    ]
