# Generated by Django 4.2.30 on 2026-04-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff_alter_user_is_superuser'),
        ('core', '0003_dataset_tables'),
    ]

    operations = [
    ]
