# Generated by Django 6.0.5 on 2026-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portfoliosnapshot_portfoliofeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgap',
            name='status',
            field=models.CharField(choices=[('pending', '분석 대기'), ('active', '학습 중'), ('resolved', '해소됨')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='problemrecommendation',
            name='platform',
            field=models.CharField(choices=[('elaw', 'ELAW 자체 문제'), ('baekjoon', '백준'), ('programmers', '프로그래머스'), ('leetcode', 'LeetCode')], max_length=20),
        ),
    ]
