# Generated by Django 6.0.4 on 2026-04-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260421_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetentry',
            name='career_level',
            field=models.CharField(choices=[('junior', '신입/주니어'), ('mid', '중간경력 (3~5년)'), ('senior', '시니어 (5년+)'), ('unknown', '미분류')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='company_name',
            field=models.CharField(help_text='기업명 예) Google', max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='curr_type_str',
            field=models.CharField(help_text='직무_경력레벨_기업 원본 문자열', max_length=200),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='dataset_id',
            field=models.UUIDField(help_text='curr_type_id (HuggingFace UUID)', unique=True),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='is_parsed',
            field=models.BooleanField(default=False, help_text='구조화 파싱 완료 여부'),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='jd_raw',
            field=models.TextField(help_text='채용공고 원문 텍스트'),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='job_title',
            field=models.CharField(default='Software Engineer', help_text='직무명 예) Software Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='resume_raw',
            field=models.TextField(help_text='이력서 원문 텍스트'),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='benefits',
            field=models.JSONField(blank=True, help_text='복리후생 리스트', null=True),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='employment_type',
            field=models.CharField(blank=True, help_text='정규직/계약직 등', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='job_posting',
            field=models.ForeignKey(blank=True, help_text='기존 JobPosting과 연계 시 사용', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_jds', to='core.jobposting'),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='preferred_skill_tags',
            field=models.JSONField(blank=True, help_text='우대 스킬 태그', null=True),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='qualifications',
            field=models.JSONField(blank=True, help_text='자격 요건 구조화', null=True),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='required_skill_tags',
            field=models.JSONField(blank=True, help_text='필수 스킬 태그 예) ["python","django"]', null=True),
        ),
        migrations.AlterField(
            model_name='datasetjobdescription',
            name='responsibilities',
            field=models.JSONField(blank=True, help_text='주요 업무 리스트', null=True),
        ),
        migrations.AlterField(
            model_name='datasetloadhistory',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0, help_text='실패한 행 수'),
        ),
        migrations.AlterField(
            model_name='datasetloadhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetloadhistory',
            name='loaded_rows',
            field=models.PositiveIntegerField(default=0, help_text='성공적으로 적재된 행 수'),
        ),
        migrations.AlterField(
            model_name='datasetloadhistory',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, help_text='전체 행 수'),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='AI 모델 예측 점수 (0~100)', null=True),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='final_score',
            field=models.FloatField(blank=True, help_text='rule_score + ai_score 가중 평균', null=True),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='is_positive',
            field=models.BooleanField(help_text='같은 entry의 resume-JD 쌍이면 True (정답)'),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='rule_score',
            field=models.FloatField(blank=True, help_text='스킬 키워드 매칭 기반 점수 (0~100)', null=True),
        ),
        migrations.AlterField(
            model_name='datasetmatchscore',
            name='score_detail',
            field=models.JSONField(blank=True, help_text='점수 세부 내역 예) {"skill_match": 60, "level_match": 20}', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='certifications',
            field=models.JSONField(blank=True, help_text='자격증 및 수상', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='education_json',
            field=models.JSONField(blank=True, help_text='학력 구조화', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='experience_json',
            field=models.JSONField(blank=True, help_text='경력 구조화', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='프로페셔널 요약', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='projects_json',
            field=models.JSONField(blank=True, help_text='프로젝트 구조화', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='skill_tags',
            field=models.JSONField(blank=True, help_text='정규화된 스킬 태그 배열 예) ["python","django","mysql"]', null=True),
        ),
        migrations.AlterField(
            model_name='datasetresume',
            name='skills_json',
            field=models.JSONField(blank=True, help_text='기술스택 구조화', null=True),
        ),
        migrations.CreateModel(
            name='JobProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question_id', models.PositiveIntegerField(help_text='파일 내 question_id (1~200)')),
                ('job_role', models.CharField(help_text='예) AI Engineer, Backend Engineer', max_length=100)),
                ('difficulty', models.CharField(choices=[('university_level', '대학 기초'), ('junior_level', '신입 수준'), ('middle_level', '중간 경력'), ('senior_level', '시니어 수준')], max_length=20)),
                ('question_type', models.CharField(blank=True, choices=[('definition', '개념 정의'), ('application', '응용'), ('debugging', '디버깅'), ('design', '설계'), ('analysis', '분석'), ('coding', '코딩')], max_length=20, null=True)),
                ('category', models.CharField(help_text='예) Machine Learning, Deep Learning', max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text='예) Evaluation, Optimization', max_length=100, null=True)),
                ('skills_required', models.JSONField(help_text='예) ["Metrics", "ROC AUC"]')),
                ('scenario', models.TextField(blank=True, help_text='문제 상황 설명', null=True)),
                ('question', models.TextField(help_text='문제 본문')),
                ('choices', models.JSONField(help_text='객관식 선택지 배열 예) ["SGD","Dropout","BN","ReLU"]')),
                ('correct_answer', models.CharField(help_text='정답 문자열', max_length=300)),
                ('explanation', models.TextField(blank=True, help_text='해설', null=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('avg_correct_rate', models.FloatField(blank=True, help_text='전체 사용자 평균 정답률', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_problems',
                'indexes': [models.Index(fields=['job_role'], name='idx_jp_job_role'), models.Index(fields=['difficulty'], name='idx_jp_difficulty'), models.Index(fields=['category', 'subcategory'], name='idx_jp_category'), models.Index(fields=['question_type'], name='idx_jp_qtype')],
                'unique_together': {('job_role', 'original_question_id')},
            },
        ),
        migrations.CreateModel(
            name='JobProblemCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('cluster_id', models.CharField(help_text='예) Deep Learning__Optimization', max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.PositiveSmallIntegerField(help_text='클러스터 내 문제 수')),
                ('question_ids', models.JSONField(help_text='original_question_id 배열 예) [2, 20, 27]')),
                ('common_skills', models.JSONField(blank=True, help_text='클러스터 내 공통 스킬 예) ["Optimizer","Adam"]', null=True)),
                ('skill_weight', models.FloatField(default=0.6)),
                ('scenario_weight', models.FloatField(default=0.4)),
                ('min_combined_score', models.FloatField(default=0.15)),
                ('same_category_bonus', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_problem_clusters',
                'indexes': [models.Index(fields=['job_role'], name='idx_jpc_job_role'), models.Index(fields=['category'], name='idx_jpc_category')],
                'unique_together': {('job_role', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100, unique=True)),
                ('source_file', models.CharField(help_text='원본 파일명 예) AI_Engineer.json', max_length=200)),
                ('total_problems', models.PositiveSmallIntegerField()),
                ('cluster_count', models.PositiveSmallIntegerField()),
                ('edge_count', models.PositiveSmallIntegerField()),
                ('isolated_problem_count', models.PositiveSmallIntegerField(help_text='어떤 클러스터에도 속하지 않는 독립 문제 수')),
                ('difficulty_distribution', models.JSONField(help_text='{"university_level":25,"junior_level":25,"middle_level":50,"senior_level":100}')),
                ('skill_weight', models.FloatField(default=0.6)),
                ('scenario_weight', models.FloatField(default=0.4)),
                ('min_combined_score', models.FloatField(default=0.15)),
                ('max_prereqs_per_target', models.PositiveSmallIntegerField(default=3)),
                ('same_category_bonus', models.FloatField(default=0.1)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_path_meta',
                'indexes': [models.Index(fields=['job_role'], name='idx_lpm_job_role')],
            },
        ),
        migrations.CreateModel(
            name='JobProblemSolveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('correct', '정답'), ('incorrect', '오답'), ('skipped', '건너뜀')], max_length=10)),
                ('selected_answer', models.CharField(blank=True, help_text='사용자가 선택한 답', max_length=300, null=True)),
                ('time_spent_sec', models.PositiveSmallIntegerField(blank=True, help_text='풀이 소요 시간 (초)', null=True)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_histories', to='core.jobproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_problem_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_problem_solve_history',
                'indexes': [models.Index(fields=['user', '-solved_at'], name='idx_jpsh_user_time'), models.Index(fields=['user', 'status'], name='idx_jpsh_user_status'), models.Index(fields=['problem'], name='idx_jpsh_problem')],
            },
        ),
        migrations.CreateModel(
            name='ProblemEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('combined_score', models.FloatField(help_text='스킬+시나리오 가중 합산 점수')),
                ('skill_overlap', models.FloatField(blank=True, help_text='스킬 겹침 정도 (0~1)', null=True)),
                ('scenario_similarity', models.FloatField(blank=True, help_text='시나리오 유사도 (0~1)', null=True)),
                ('is_prerequisite', models.BooleanField(default=False, help_text='True면 source를 먼저 풀어야 target 이해 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_problem', models.ForeignKey(help_text='선수 문제 (먼저 풀어야 하는 문제)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.jobproblem')),
                ('target_problem', models.ForeignKey(help_text='후속 문제 (나중에 풀 문제)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.jobproblem')),
            ],
            options={
                'db_table': 'problem_edges',
                'indexes': [models.Index(fields=['job_role'], name='idx_pe_job_role'), models.Index(fields=['is_prerequisite'], name='idx_pe_prereq'), models.Index(fields=['-combined_score'], name='idx_pe_score'), models.Index(fields=['target_problem'], name='idx_pe_target')],
                'unique_together': {('source_problem', 'target_problem')},
            },
        ),
    ]
