# Generated by Django 6.0.4 on 2026-04-26 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_datasetentry_career_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_resume', models.JSONField(blank=True, null=True)),
                ('skill_analysis', models.JSONField(blank=True, null=True)),
                ('problem_history', models.JSONField(blank=True, null=True)),
                ('generated_content', models.JSONField(blank=True, null=True)),
                ('generation_method', models.CharField(choices=[('gemini', 'Gemini API'), ('model_v1', '자체 모델 v1'), ('model_v2', '자체 모델 v2 (RLHF)'), ('manual', '수동 편집')], default='gemini', max_length=20)),
                ('generation_prompt', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_final', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.portfolio')),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_snapshots', to='core.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_snapshots',
            },
        ),
        migrations.CreateModel(
            name='PortfolioFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '매우 불만족'), (2, '불만족'), (3, '보통'), (4, '만족'), (5, '매우 만족')])),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('edited_content', models.JSONField(blank=True, null=True)),
                ('rlhf_labels', models.JSONField(blank=True, null=True)),
                ('used_for_training', models.BooleanField(default=False)),
                ('training_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.portfoliosnapshot')),
            ],
            options={
                'db_table': 'portfolio_feedback',
            },
        ),
        migrations.CreateModel(
            name='ProblemRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(help_text='플랫폼 내 문제 ID', max_length=100)),
                ('platform', models.CharField(choices=[('baekjoon', '백준'), ('programmers', '프로그래머스'), ('leetcode', 'LeetCode')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('algo_tags', models.JSONField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=30, null=True)),
                ('relevance_score', models.FloatField(help_text='추천 관련성 점수 (0~1)')),
                ('reason', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', '미도전'), ('solved', '풀이 완료'), ('skipped', '건너뜀')], default='pending', max_length=10)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('posting', models.ForeignKey(blank=True, help_text='어떤 채용공고를 목표로 추천됐는지', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_recommendations', to='core.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_recommendations',
            },
        ),
        migrations.AddField(
            model_name='jobproblemsolvehistory',
            name='from_recommendation',
            field=models.ForeignKey(blank=True, help_text='어떤 추천을 통해 풀었는지', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solve_results', to='core.problemrecommendation'),
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(blank=True, max_length=30, null=True)),
                ('current_level', models.FloatField()),
                ('required_level', models.FloatField()),
                ('gap_score', models.FloatField()),
                ('recommended_problem_ids', models.JSONField(blank=True, null=True)),
                ('calculation_method', models.CharField(default='rule_based', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gaps', to='core.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_gaps',
            },
        ),
        migrations.AddField(
            model_name='problemrecommendation',
            name='skill_gap',
            field=models.ForeignKey(blank=True, help_text='어떤 스킬 갭을 채우기 위한 추천인지', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.skillgap'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', 'is_final'], name='idx_ps_user_final'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['portfolio', 'version'], name='idx_ps_version'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['generation_method'], name='idx_ps_method'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['generated_at'], name='idx_ps_generated_at'),
        ),
        migrations.AddIndex(
            model_name='portfoliofeedback',
            index=models.Index(fields=['used_for_training'], name='idx_pf_training'),
        ),
        migrations.AddIndex(
            model_name='portfoliofeedback',
            index=models.Index(fields=['rating'], name='idx_pf_rating'),
        ),
        migrations.AddIndex(
            model_name='portfoliofeedback',
            index=models.Index(fields=['created_at'], name='idx_pf_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliofeedback',
            unique_together={('snapshot', 'user')},
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['user', 'posting'], name='idx_sg_user_posting'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['-gap_score'], name='idx_sg_gap_score'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['skill_category'], name='idx_sg_category'),
        ),
        migrations.AlterUniqueTogether(
            name='skillgap',
            unique_together={('user', 'posting', 'skill_name')},
        ),
        migrations.AddIndex(
            model_name='problemrecommendation',
            index=models.Index(fields=['user', 'status'], name='idx_pr_user_status'),
        ),
        migrations.AddIndex(
            model_name='problemrecommendation',
            index=models.Index(fields=['user', 'posting'], name='idx_pr_user_posting'),
        ),
        migrations.AddIndex(
            model_name='problemrecommendation',
            index=models.Index(fields=['-relevance_score'], name='idx_pr_relevance'),
        ),
        migrations.AddIndex(
            model_name='problemrecommendation',
            index=models.Index(fields=['recommended_at'], name='idx_pr_recommended_at'),
        ),
        migrations.AlterUniqueTogether(
            name='problemrecommendation',
            unique_together={('user', 'platform', 'problem_id', 'posting')},
        ),
    ]
