# Generated by Django 6.0.5 on 2026-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobproblem',
            name='question_type',
            field=models.CharField(blank=True, choices=[('definition', '개념 정의'), ('application', '응용'), ('debugging', '디버깅'), ('design', '설계'), ('analysis', '분석'), ('coding', '코딩')], max_length=50, null=True),
        ),
    ]
